// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccaiyhrfquhlrkovmusd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjYWl5aHJmcXVobHJrb3ZtdXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDgxNDQsImV4cCI6MjA3NDAyNDE0NH0.w3kEJBqHnM9IUdcHknQsC23ePC3pzhJhm_Y_pcm9fcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});